/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R18IndexRouteImport } from './routes/r18/index'
import { Route as DetailNcodeRouteImport } from './routes/detail/$ncode'
import { Route as CustomChar123TypeChar125RouteImport } from './routes/custom/{-$type}'
import { Route as RankingChar123TypeChar125Char123DateChar125RouteImport } from './routes/ranking/{-$type}/{-$date}'
import { Route as R18RankingChar123TypeChar125RouteImport } from './routes/r18/ranking/{-$type}'
import { Route as R18DetailNcodeRouteImport } from './routes/r18/detail/$ncode'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R18IndexRoute = R18IndexRouteImport.update({
  id: '/r18/',
  path: '/r18/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailNcodeRoute = DetailNcodeRouteImport.update({
  id: '/detail/$ncode',
  path: '/detail/$ncode',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomChar123TypeChar125Route =
  CustomChar123TypeChar125RouteImport.update({
    id: '/custom/{-$type}',
    path: '/custom/{-$type}',
    getParentRoute: () => rootRouteImport,
  } as any)
const RankingChar123TypeChar125Char123DateChar125Route =
  RankingChar123TypeChar125Char123DateChar125RouteImport.update({
    id: '/ranking/{-$type}/{-$date}',
    path: '/ranking/{-$type}/{-$date}',
    getParentRoute: () => rootRouteImport,
  } as any)
const R18RankingChar123TypeChar125Route =
  R18RankingChar123TypeChar125RouteImport.update({
    id: '/r18/ranking/{-$type}',
    path: '/r18/ranking/{-$type}',
    getParentRoute: () => rootRouteImport,
  } as any)
const R18DetailNcodeRoute = R18DetailNcodeRouteImport.update({
  id: '/r18/detail/$ncode',
  path: '/r18/detail/$ncode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom/{-$type}': typeof CustomChar123TypeChar125Route
  '/detail/$ncode': typeof DetailNcodeRoute
  '/r18': typeof R18IndexRoute
  '/r18/detail/$ncode': typeof R18DetailNcodeRoute
  '/r18/ranking/{-$type}': typeof R18RankingChar123TypeChar125Route
  '/ranking/{-$type}/{-$date}': typeof RankingChar123TypeChar125Char123DateChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom/{-$type}': typeof CustomChar123TypeChar125Route
  '/detail/$ncode': typeof DetailNcodeRoute
  '/r18': typeof R18IndexRoute
  '/r18/detail/$ncode': typeof R18DetailNcodeRoute
  '/r18/ranking/{-$type}': typeof R18RankingChar123TypeChar125Route
  '/ranking/{-$type}/{-$date}': typeof RankingChar123TypeChar125Char123DateChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom/{-$type}': typeof CustomChar123TypeChar125Route
  '/detail/$ncode': typeof DetailNcodeRoute
  '/r18/': typeof R18IndexRoute
  '/r18/detail/$ncode': typeof R18DetailNcodeRoute
  '/r18/ranking/{-$type}': typeof R18RankingChar123TypeChar125Route
  '/ranking/{-$type}/{-$date}': typeof RankingChar123TypeChar125Char123DateChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/custom/{-$type}'
    | '/detail/$ncode'
    | '/r18'
    | '/r18/detail/$ncode'
    | '/r18/ranking/{-$type}'
    | '/ranking/{-$type}/{-$date}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/custom/{-$type}'
    | '/detail/$ncode'
    | '/r18'
    | '/r18/detail/$ncode'
    | '/r18/ranking/{-$type}'
    | '/ranking/{-$type}/{-$date}'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/custom/{-$type}'
    | '/detail/$ncode'
    | '/r18/'
    | '/r18/detail/$ncode'
    | '/r18/ranking/{-$type}'
    | '/ranking/{-$type}/{-$date}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomChar123TypeChar125Route: typeof CustomChar123TypeChar125Route
  DetailNcodeRoute: typeof DetailNcodeRoute
  R18IndexRoute: typeof R18IndexRoute
  R18DetailNcodeRoute: typeof R18DetailNcodeRoute
  R18RankingChar123TypeChar125Route: typeof R18RankingChar123TypeChar125Route
  RankingChar123TypeChar125Char123DateChar125Route: typeof RankingChar123TypeChar125Char123DateChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r18/': {
      id: '/r18/'
      path: '/r18'
      fullPath: '/r18'
      preLoaderRoute: typeof R18IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$ncode': {
      id: '/detail/$ncode'
      path: '/detail/$ncode'
      fullPath: '/detail/$ncode'
      preLoaderRoute: typeof DetailNcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/{-$type}': {
      id: '/custom/{-$type}'
      path: '/custom/{-$type}'
      fullPath: '/custom/{-$type}'
      preLoaderRoute: typeof CustomChar123TypeChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/{-$type}/{-$date}': {
      id: '/ranking/{-$type}/{-$date}'
      path: '/ranking/{-$type}/{-$date}'
      fullPath: '/ranking/{-$type}/{-$date}'
      preLoaderRoute: typeof RankingChar123TypeChar125Char123DateChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r18/ranking/{-$type}': {
      id: '/r18/ranking/{-$type}'
      path: '/r18/ranking/{-$type}'
      fullPath: '/r18/ranking/{-$type}'
      preLoaderRoute: typeof R18RankingChar123TypeChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r18/detail/$ncode': {
      id: '/r18/detail/$ncode'
      path: '/r18/detail/$ncode'
      fullPath: '/r18/detail/$ncode'
      preLoaderRoute: typeof R18DetailNcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomChar123TypeChar125Route: CustomChar123TypeChar125Route,
  DetailNcodeRoute: DetailNcodeRoute,
  R18IndexRoute: R18IndexRoute,
  R18DetailNcodeRoute: R18DetailNcodeRoute,
  R18RankingChar123TypeChar125Route: R18RankingChar123TypeChar125Route,
  RankingChar123TypeChar125Char123DateChar125Route:
    RankingChar123TypeChar125Char123DateChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
